/*
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ChannelmanagerChannelResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChannelmanagerMarketResponseWithAssociationsAssociation
 */
public class ChannelmanagerMarketResponseWithAssociationsAssociationTest {
    private final ChannelmanagerMarketResponseWithAssociationsAssociation model = new ChannelmanagerMarketResponseWithAssociationsAssociation();

    /**
     * Model tests for ChannelmanagerMarketResponseWithAssociationsAssociation
     */
    @Test
    public void testChannelmanagerMarketResponseWithAssociationsAssociation() {
        // TODO: test ChannelmanagerMarketResponseWithAssociationsAssociation
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

}
