/*
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ChannelmanagerMarketResponseWithAssociations;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChannelmanagerListMarketsWithAssociationsResponse
 */
public class ChannelmanagerListMarketsWithAssociationsResponseTest {
    private final ChannelmanagerListMarketsWithAssociationsResponse model = new ChannelmanagerListMarketsWithAssociationsResponse();

    /**
     * Model tests for ChannelmanagerListMarketsWithAssociationsResponse
     */
    @Test
    public void testChannelmanagerListMarketsWithAssociationsResponse() {
        // TODO: test ChannelmanagerListMarketsWithAssociationsResponse
    }

    /**
     * Test the property 'markets'
     */
    @Test
    public void marketsTest() {
        // TODO: test markets
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
