/*
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChannelmanagerCreateAssociationRequest
 */
public class ChannelmanagerCreateAssociationRequestTest {
    private final ChannelmanagerCreateAssociationRequest model = new ChannelmanagerCreateAssociationRequest();

    /**
     * Model tests for ChannelmanagerCreateAssociationRequest
     */
    @Test
    public void testChannelmanagerCreateAssociationRequest() {
        // TODO: test ChannelmanagerCreateAssociationRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'channelGrn'
     */
    @Test
    public void channelGrnTest() {
        // TODO: test channelGrn
    }

    /**
     * Test the property 'marketGrn'
     */
    @Test
    public void marketGrnTest() {
        // TODO: test marketGrn
    }

}
