/*
 * Channel Manager Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_ChannelManager.JSON;

/**
 * ChannelmanagerChannelSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-08T15:00:20.871956445Z[Etc/UTC]")
public class ChannelmanagerChannelSettings {
  public static final String SERIALIZED_NAME_HIDE_OOS_PRODUCTS = "hideOosProducts";
  @SerializedName(SERIALIZED_NAME_HIDE_OOS_PRODUCTS)
  private Boolean hideOosProducts;

  public static final String SERIALIZED_NAME_HIDE_PRICELESS_PRODUCTS = "hidePricelessProducts";
  @SerializedName(SERIALIZED_NAME_HIDE_PRICELESS_PRODUCTS)
  private Boolean hidePricelessProducts;

  public ChannelmanagerChannelSettings() {
  }

  public ChannelmanagerChannelSettings hideOosProducts(Boolean hideOosProducts) {
    this.hideOosProducts = hideOosProducts;
    return this;
  }

   /**
   * Get hideOosProducts
   * @return hideOosProducts
  **/
  @javax.annotation.Nullable
  public Boolean getHideOosProducts() {
    return hideOosProducts;
  }

  public void setHideOosProducts(Boolean hideOosProducts) {
    this.hideOosProducts = hideOosProducts;
  }


  public ChannelmanagerChannelSettings hidePricelessProducts(Boolean hidePricelessProducts) {
    this.hidePricelessProducts = hidePricelessProducts;
    return this;
  }

   /**
   * Get hidePricelessProducts
   * @return hidePricelessProducts
  **/
  @javax.annotation.Nullable
  public Boolean getHidePricelessProducts() {
    return hidePricelessProducts;
  }

  public void setHidePricelessProducts(Boolean hidePricelessProducts) {
    this.hidePricelessProducts = hidePricelessProducts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelmanagerChannelSettings channelmanagerChannelSettings = (ChannelmanagerChannelSettings) o;
    return Objects.equals(this.hideOosProducts, channelmanagerChannelSettings.hideOosProducts) &&
        Objects.equals(this.hidePricelessProducts, channelmanagerChannelSettings.hidePricelessProducts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hideOosProducts, hidePricelessProducts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelmanagerChannelSettings {\n");
    sb.append("    hideOosProducts: ").append(toIndentedString(hideOosProducts)).append("\n");
    sb.append("    hidePricelessProducts: ").append(toIndentedString(hidePricelessProducts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("hideOosProducts");
    openapiFields.add("hidePricelessProducts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ChannelmanagerChannelSettings
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChannelmanagerChannelSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChannelmanagerChannelSettings is not found in the empty JSON string", ChannelmanagerChannelSettings.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChannelmanagerChannelSettings.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChannelmanagerChannelSettings` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChannelmanagerChannelSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChannelmanagerChannelSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChannelmanagerChannelSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChannelmanagerChannelSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<ChannelmanagerChannelSettings>() {
           @Override
           public void write(JsonWriter out, ChannelmanagerChannelSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChannelmanagerChannelSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChannelmanagerChannelSettings given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChannelmanagerChannelSettings
  * @throws IOException if the JSON string is invalid with respect to ChannelmanagerChannelSettings
  */
  public static ChannelmanagerChannelSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChannelmanagerChannelSettings.class);
  }

 /**
  * Convert an instance of ChannelmanagerChannelSettings to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

